### ISSUE TITLE
ProcessManager.start's first argument should be List<String> not List<dynamic>

### ISSUE THREAD

**Issue by Hixie** [google/process.dart#10]
I'm implementing `ProcessManager.start` and I don't understand what type I could receive in the first argument's list other than String, nor what to do with any other types.

**Comment by tvolkert** [comment]
It's intentional - see https://github.com/google/process.dart/blob/master/lib/src/record_replay/command_element.dart

We could probably document that better in the interface.

**Comment by Hixie** [comment]
Ah, yeah, that should definitely be documented.

Should I be worrying about CommandElement in my mock for ProcessManager?

**Comment by tvolkert** [comment]
Nope

**Comment by stuartmorgan-g** [comment]
Closing, as this package now lives in flutter/packages. Please file an [issue in the Flutter issue tracker](https://github.com/flutter/flutter/issues) if this is still an issue.
