### ISSUE TITLE
Upgrade from comment-based generics syntax

### ISSUE THREAD

**Issue by srawlins** [google/process.dart#13]
The comment-based generics syntax will be removed from the Dart SDK tools (like DDC, analyzer) "soon." dart-lang/sdk#28796

Such syntax (like in [_areListsEqual](https://github.com/google/process.dart/blob/master/lib/src/record_replay/manifest.dart#L13)) needs to be updated, and the minimum Dart SDK in [pubspec.yaml](https://github.com/google/process.dart/blob/master/pubspec.yaml#L20) needs to be bumped to 1.21, when the [real, non-comment-based syntax was introduced](http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html).

**Comment by goderbauer** [comment]
Fixed by #14.
