### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [google/process.dart#26]
Running tests in Dart 2 mode, see the following failure

00:02 +0 -2: RecordingProcessManager run [E]                                                                                                                                                           
  type 'List<dynamic>' is not a subtype of type 'List<String>' where
    List is from dart:core
    List is from dart:core
    String is from dart:core
  
  package:process/src/record_replay/common.dart 15:6                       sanitize
  package:process/src/record_replay/recording_process_manager.dart 147:37  RecordingProcessManager.run
  ===== asynchronous gap ===========================
  dart:async                                                               _Completer.completeError
  package:process/src/record_replay/recording_process_manager.dart         RecordingProcessManager.run
  ===== asynchronous gap ===========================
  dart:async                                                               _asyncThenWrapperHelper
  package:process/src/record_replay/recording_process_manager.dart         RecordingProcessManager.run
  ../../tmp/archives/third_party/dart/process/test/record_test.dart 65:25  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                               new Future.microtask
  ../../process/test/record_test.dart 63:17  main.<fn>.<fn>

**Comment by stuartmorgan-g** [comment]
Closing as obsolete; tests are passing.
