### ISSUE TITLE
Pubspec doesn't declare Dart 2.0 SDK support

### ISSUE THREAD

**Issue by mit-mit** [google/process.dart#31]
The published version of process doesn't support Dart 2:
https://pub.dartlang.org/packages/process#-analysis-tab-

However, looks like the pubspec in this repo does, so do we need to republish?

Also, there seems to be analysis issues: https://github.com/google/process.dart/issues/26

**Comment by mit-mit** [comment]
cc @tvolkert

**Comment by tvolkert** [comment]
This is fixed now
