### ISSUE TITLE
Please publish a new version, which is compatible with Dart SDK ^2.1.0

### ISSUE THREAD

**Issue by mkustermann** [google/process.dart#32]
The next flutter/engine -> flutter/flutter roll will receive a new 2.1.0-dev Dart SDK, which requires us to upgrade all 3rd party packages. Most of them have already newer versions published which are compatible with Dart 2, but the latest commits to this `package:process` repository haven't been published yet.

@tvolkert @goderbauer Would you mind publishing a new version? (This is blocking https://github.com/flutter/flutter/pull/20427)

**Comment by tvolkert** [comment]
Done

**Comment by mkustermann** [comment]
Thanks for the quick action, @tvolkert :+1:
