### ISSUE TITLE
ProcessManager.run should check if the executable is an absolute path and not do its attempts to lookup the path etc. if it is

### ISSUE THREAD

**Issue by dnfield** [google/process.dart#55]
For example, `processManager.run(<String>['/path/to/a/binary', 'arg1', 'arg2']);` is going through this code path: https://github.com/google/process.dart/blob/master/lib/src/interface/local_process_manager.dart#L122 when I don't use `runInShell`.

I don't want to use `runInShell` though, I want it to just run the command to a process I have the abspath for.

**Comment by stuartmorgan-g** [comment]
Closing, as this package now lives in flutter/packages. Please file an [issue in the Flutter issue tracker](https://github.com/flutter/flutter/issues) if this is still an issue.
