### ISSUE TITLE
getExecutablePath should only return executables

### ISSUE THREAD

**Issue by gspencergoog** [google/process.dart#60]
Right now, if I have the directory `/tmp/bin` in my PATH before `/usr/bin`, and it has a text file (mod 644, i.e. executable bit NOT set) in it called `patch`, then if I attempt to run 'patch' using `Process.run` or `Process.start`, then it will fail, because even though an executable `patch` exists in the PATH at `/usr/bin/patch`, it finds the one in `/tmp/bin/patch` instead and tries to execute it. It will succeed just fine if `runInShell` is set, since the shell skips non-executables.

getExecutablePath should, at least on Unix-like systems, only return files that have their executable bit set.

**Comment by stuartmorgan-g** [comment]
Closing, as this package now lives in flutter/packages. Please file an [issue in the Flutter issue tracker](https://github.com/flutter/flutter/issues) if this is still an issue.
