### ISSUE TITLE
ProcessManager.run* should throw ProcessException if executable not found

### ISSUE THREAD

**Issue by tvolkert** [google/process.dart#7]
As of https://github.com/google/process.dart/pull/3, it throws ArgumentError instead.

/cc @goderbauer

**Comment by tvolkert** [comment]
The native `dart:io` code throws the following:

```
ProcessException: No such file or directory
  Command: <cmd>
```

Whereas we're throwing:

```
Invalid argument(s): Cannot find executable for <cmd>
```

**Comment by CedX** [comment]
+1 for providing the `ProcessException` in this package.

**Comment by tvolkert** [comment]
@cedx you game to submit a PR?  https://github.com/google/process.dart/blob/master/CONTRIBUTING.md

**Comment by CedX** [comment]
@tvolkert Done :smile:

**Comment by stuartmorgan-g** [comment]
Closing, as this package now lives in flutter/packages. Please file an [issue in the Flutter issue tracker](https://github.com/flutter/flutter/issues) if this is still an issue.
