### ISSUE TITLE
Where is the record-replay functionality

### ISSUE THREAD

**Issue by bartekpacia** [google/process.dart#73]
The readme talks about

> Comes with a record-replay implementation out-of-the-box, making it super easy to test code that spawns processes in a hermetic way.

but I couldn't find any info about it except that it was removed.

See also:
- https://github.com/google/process.dart/pull/47

**Comment by stuartmorgan-g** [comment]
Closing, as this package now lives in flutter/packages. Please file an [issue in the Flutter issue tracker](https://github.com/flutter/flutter/issues) if this is still an issue.
